- name: restart postgresql
  ansible.builtin.systemd_service:
    name: postgresql
    state: restarted

- name: reload postgresql
  ansible.builtin.systemd_service:
    name: postgresql
    state: reloaded
